import type { Metadata } from 'next';
import './globals.css';
import { ThemeProvider } from '@/context/theme'; // @ : 專案根目錄
import ThemeSwitch from './_components/theme-switch';

export const metadata: Metadata = {
  title: 'React 課程範例',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-full flex flex-col">
        {/* 在根元件包上 provider，提供context給底下所有頁面 */}
        <ThemeProvider>
          <ThemeSwitch />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
