import type { Metadata } from 'next';
// 導入客戶端元件
import CartIcon from '../cart-v2/_components/cart-icon';

export const metadata: Metadata = {
  title: '購物商城',
  description: 'Generated by create next app',
};

export default function ShopLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <CartIcon />
      {children}
    </>
  );
}
